export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCTS_SUCCESSFUL = 'GET_PRODUCTS_SUCCESSFUL';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QTY = 'INCREASE_QTY';
export const DECRESS_QTY = 'DECRESS_QTY';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESSFUL = 'CREATE_USER_SUCCESSFUL';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESSFUL = 'GET_USER_SUCCESSFUL';
export const GET_USER_ERROR = 'GET_USER_ERROR';
